# Changes here will be overwritten by Copier
_commit: v3.3.0
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
codeowner_username: '@stkr22'
copyright_license: GPL-3.0
github_repository_name: mqtt-ingest-pipeline-py
github_username: stkr22
project_description: Collection of MQTT data transformers for home automation and
    IoT devices.
project_name: MQTT Ingest Pipeline
publish_to_pypi: true
python_package_distribution_name: mqtt-ingest-pipeline
python_package_import_name: mqtt_ingest_pipeline
python_package_version: 0.1.2
use_containers: true
