FROM mcr.microsoft.com/devcontainers/python@sha256:f84dde6b1993dca054dbeab997220a1e346ac1c6bf08af1f69412e47ac1d2200
COPY --from=ghcr.io/astral-sh/uv:0.5.7 /uv /uvx /bin/
ENV VIRTUAL_ENV=/workspaces/.venv
ENV UV_PROJECT_ENVIRONMENT=/workspaces/.venv
RUN mkdir -p /workspaces && \
    uv venv /workspaces/.venv && \
    chown -R vscode:vscode /workspaces/.venv
USER vscode
