FROM mcr.microsoft.com/devcontainers/python@sha256:12d0e90a47be8b1c6e2a77a8a44e86c0b35a599e0ed422437680a3800c4f1524
COPY --from=ghcr.io/astral-sh/uv:0.5.7 /uv /uvx /bin/
ENV VIRTUAL_ENV=/workspaces/.venv
ENV UV_PROJECT_ENVIRONMENT=/workspaces/.venv
RUN mkdir -p /workspaces && \
    uv venv /workspaces/.venv && \
    chown -R vscode:vscode /workspaces/.venv
USER vscode
